version: "3.3"

services:
  client:
    container_name: 9ty-client
    image: 9ty-client:latest
    ports:
      - "9090:8080"
    environment:
      CLIENT_PORT_DOMAIN_GRPC_HOST: "9ty-server:9091"
      CLIENT_HTTP_HOST: ":8080"
      CLIENT_PORT_DATA_JSON_FILE: "./ports.json"
    deploy:
      resources:
        limits:
          memory: 200M

  server:
    container_name: 9ty-server
    image: 9ty-server:latest
    ports:
      - 9091:8080
    environment:
      PORT_DOMAIN_GRPC_HOST: ":9091"
